apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-website
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: blue-website
    repoURL: 'https://github.com/zeynep-bilgehan/test.git'
    targetRevision: HEAD
  project: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingress
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: test/overlays/grafana
    repoURL: 'https://github.com/zeynep-bilgehan/test.git'
    targetRevision: HEAD
  project: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: test/overlays/argocd
    repoURL: 'https://github.com/zeynep-bilgehan/test.git'
    targetRevision: HEAD
  project: default
