apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: green-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/zeynep-bilgehan/test.git
    targetRevision: HEAD
    path: green-website
    repoURL: 'https://github.com/zeynep-bilgehan/minikube.git'
  destination:
    server: https://kubernetes.default.svc
    namespace: webservers

  syncPolicy:
    automated:
      prune: true
      selfHeal: true


---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blue-website
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: blue-website
    repoURL: 'https://github.com/zeynep-bilgehan/minikube.git'
    targetRevision: HEAD
  project: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: test/overlays/grafana
    repoURL: 'https://github.com/zeynep-bilgehan/minikube.git'
    targetRevision: HEAD
  project: default

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ingress
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: test/overlays/argocd
    repoURL: 'https://github.com/zeynep-bilgehan/minikube.git'
    targetRevision: HEAD
  project: default
